services:

  backend:
    build: ./backend
    container_name: opspilot_backend

    command: >
      sh -c "
      while ! nc -z db 5432;
      do
        echo 'Waiting for PostgreSQL...';
        sleep 1;
      done;

      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: opspilot_frontend

    volumes:
      - ./frontend:/app
      - /app/node_modules

    ports:
      - "5173:5173"

    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: opspilot_db

    environment:
      POSTGRES_DB: opspilot
      POSTGRES_USER: opspilotuser
      POSTGRES_PASSWORD: opspilotpass

    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:
